# Generated by Django 6.0.6 on 2026-09-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='product',
            name='sunlight',
            field=models.CharField(choices=[('low', 'Low Light'), ('indirect', 'Bright Indirect Light'), ('partial', 'Partial Sun'), ('full', 'Full Sun')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='watering',
            field=models.CharField(choices=[('rare', 'Rarely'), ('weekly', 'Once a Week'), ('biweekly', 'Every 1–2 Weeks'), ('frequent', 'Frequently')], max_length=50),
        ),
    ]
